services:
  pilot-api-dotnet-mssql:
    container_name: pilot-api-dotnet-mssql
    image: pilot-api-dotnet-mssql:1.0
    build:
      context: ${WORKING_DIR}/api-dotnet-mssql
      dockerfile: ../../Docker/Api_dotnet/dockerfile_mssql
      args:
        DEPLOY_DATE: ${CURRENT_DATE}
        APP_PORT: ${DOTNET_MSSQL_PORT:-55101}
    ports:
      - "${DOTNET_MSSQL_PORT:-55101}:8080"
    mem_limit: 1g
    networks:
      - pilot-net

  pilot-api-dotnet-postgres:
    container_name: pilot-api-dotnet-postgres
    image: pilot-api-dotnet-postgres:1.0
    build:
      context: ${WORKING_DIR}/api-dotnet-postgres
      dockerfile: ../../Docker/Api_dotnet/dockerfile_postgres
      args:
        DEPLOY_DATE: ${CURRENT_DATE}
        APP_PORT: ${DOTNET_POSTGRES_PORT:-55201}
    ports:
      - "${DOTNET_POSTGRES_PORT:-55201}:8080"
    mem_limit: 1g
    networks:
      - pilot-net

networks:
  pilot-net:
    external: true
    name: pilot-net
